//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDisplay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientDisplay.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character buffer overrun..
        /// </summary>
        internal static string Character_buffer_overrun_ {
            get {
                return ResourceManager.GetString("Character_buffer_overrun_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framing error..
        /// </summary>
        internal static string Framing_error_ {
            get {
                return ResourceManager.GetString("Framing_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input buffer overflow..
        /// </summary>
        internal static string Input_buffer_overflow_ {
            get {
                return ResourceManager.GetString("Input_buffer_overflow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output buffer full..
        /// </summary>
        internal static string Output_buffer_full_ {
            get {
                return ResourceManager.GetString("Output_buffer_full_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity error..
        /// </summary>
        internal static string Parity_error_ {
            get {
                return ResourceManager.GetString("Parity_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference File Received.
        /// </summary>
        internal static string ReferenceFileReceived {
            get {
                return ResourceManager.GetString("ReferenceFileReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference File Written : .
        /// </summary>
        internal static string ReferenceFileWritten {
            get {
                return ResourceManager.GetString("ReferenceFileWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
