//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorDisplay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorDisplay.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onuchin@cern.ch.
        /// </summary>
        internal static string AboutBox_AboutBox_onuchin_cern_ch {
            get {
                return ResourceManager.GetString("AboutBox_AboutBox_onuchin_cern_ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАО ПРОТОМ.
        /// </summary>
        internal static string AboutBox_AboutBox_ЗАО_ПРОТОМ {
            get {
                return ResourceManager.GetString("AboutBox_AboutBox_ЗАО_ПРОТОМ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль положения пациента.
        /// </summary>
        internal static string AboutBox_AboutBox_Контроль_положения_пациента {
            get {
                return ResourceManager.GetString("AboutBox_AboutBox_Контроль_положения_пациента", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук выключен. Включить микрофон.
        /// </summary>
        internal static string AudioOftooltip {
            get {
                return ResourceManager.GetString("AudioOftooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук включен   .
        /// </summary>
        internal static string AudioOn {
            get {
                return ResourceManager.GetString("AudioOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата  рожд..
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индикатор дыхания.
        /// </summary>
        internal static string BreathDetector {
            get {
                return ResourceManager.GetString("BreathDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение ок.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка создания новой записи в базе данных.
        /// </summary>
        internal static string DbInsertError {
            get {
                return ResourceManager.GetString("DbInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим отображения.
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Display.
        /// </summary>
        internal static string Doctor_Display {
            get {
                return ResourceManager.GetString("Doctor_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не отображать разницу .
        /// </summary>
        internal static string DontShowDiff {
            get {
                return ResourceManager.GetString("DontShowDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не доступен :.
        /// </summary>
        internal static string FailFileAccess {
            get {
                return ResourceManager.GetString("FailFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        internal static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль положения пациента.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроллер не подключен.
        /// </summary>
        internal static string GamepadCon {
            get {
                return ResourceManager.GetString("GamepadCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководство.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководство пользователя (F1).
        /// </summary>
        internal static string HelpEx {
            get {
                return ResourceManager.GetString("HelpEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   загружено..
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить изображение.
        /// </summary>
        internal static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить реперный снимок из базы данных.
        /// </summary>
        internal static string LoadImageEx {
            get {
                return ResourceManager.GetString("LoadImageEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки реперного изображения : .
        /// </summary>
        internal static string LoadRefImageError {
            get {
                return ResourceManager.GetString("LoadRefImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сеть недоступна! Проверьте сетевой разъём..
        /// </summary>
        internal static string NetworkBroken {
            get {
                return ResourceManager.GetString("NetworkBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет соединения с компьютером пациента.
        /// </summary>
        internal static string NoPatientConnection {
            get {
                return ResourceManager.GetString("NoPatientConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует запись о файле в базе данных. Выберете нужный файл ....
        /// </summary>
        internal static string NoRefImageInDb {
            get {
                return ResourceManager.GetString("NoRefImageInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук включен. Отключить микрофон..
        /// </summary>
        internal static string OffAudio {
            get {
                return ResourceManager.GetString("OffAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap on1 {
            get {
                object obj = ResourceManager.GetObject("on1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук выключен.
        /// </summary>
        internal static string OnAudio {
            get {
                return ResourceManager.GetString("OnAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Files(*.jpg)|*.jpg|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID пациента.
        /// </summary>
        internal static string PatientID {
            get {
                return ResourceManager.GetString("PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компьютер пациента отсоединился! Необходимо проверить включен ли нетбук рассположенный рядом с креслом пациента..
        /// </summary>
        internal static string PatientLeaved {
            get {
                return ResourceManager.GetString("PatientLeaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим фиксации положения пациента.
        /// </summary>
        internal static string PatientPositionFixMode {
            get {
                return ResourceManager.GetString("PatientPositionFixMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Выберите зону интереса двигая желтую и синюю линии.
        /// </summary>
        internal static string PatientPositionFixText1 {
            get {
                return ResourceManager.GetString("PatientPositionFixText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Увеличьте зону интереса нажав кнопку &quot;Увеличить видео&quot;.
        /// </summary>
        internal static string PatientPositionFixText2 {
            get {
                return ResourceManager.GetString("PatientPositionFixText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Сделайте снимок реперного изображения нажав кнопку &quot;Фиксировать&quot;.
        /// </summary>
        internal static string PatientPositionFixText3 {
            get {
                return ResourceManager.GetString("PatientPositionFixText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Сохраните реперное изображение в базе данных нажав кнопку &quot;Сохранить&quot;.
        /// </summary>
        internal static string PatientPositionFixText4 {
            get {
                return ResourceManager.GetString("PatientPositionFixText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим верификации положения пациента.
        /// </summary>
        internal static string PatientPositionVerifyMode {
            get {
                return ResourceManager.GetString("PatientPositionVerifyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. загрузите реперное изображение из базы данных нажав кнопку &quot;Загрузить изображение&quot;.
        /// </summary>
        internal static string PatientPositionVerifyText1 {
            get {
                return ResourceManager.GetString("PatientPositionVerifyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. откорректируйте положение пациента так, чтобы &quot;Уровень красного&quot; был  &quot;зелёным&quot; &lt; 10.
        /// </summary>
        internal static string PatientPositionVerifyText2 {
            get {
                return ResourceManager.GetString("PatientPositionVerifyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. в процессе облучения &quot;Уровень красного&quot; должен быть &quot;зелёным&quot; &lt; 10.
        /// </summary>
        internal static string PatientPositionVerifyText3 {
            get {
                return ResourceManager.GetString("PatientPositionVerifyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin {
            get {
                object obj = ResourceManager.GetObject("pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin2 {
            get {
                object obj = ResourceManager.GetObject("pin2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль положения пациента.
        /// </summary>
        internal static string ProgDescription {
            get {
                return ResourceManager.GetString("ProgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень красного.
        /// </summary>
        internal static string RedLevel {
            get {
                return ResourceManager.GetString("RedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реперное изображение получено .
        /// </summary>
        internal static string ReferenceFileReceived {
            get {
                return ResourceManager.GetString("ReferenceFileReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реперное изображение - .
        /// </summary>
        internal static string RefFile {
            get {
                return ResourceManager.GetString("RefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Сброс.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс увеличения и реперного снимка .
        /// </summary>
        internal static string ResetEx {
            get {
                return ResourceManager.GetString("ResetEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить реперный снимок в базе данных\r\n.
        /// </summary>
        internal static string SaveEx {
            get {
                return ResourceManager.GetString("SaveEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить снимок ....
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при сохранении снимка.
        /// </summary>
        internal static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG file (*.jpg)|.
        /// </summary>
        internal static string SaveFileTypes {
            get {
                return ResourceManager.GetString("SaveFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало пересылки файла .
        /// </summary>
        internal static string SendingFile {
            get {
                return ResourceManager.GetString("SendingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать разницу .
        /// </summary>
        internal static string ShowDiff {
            get {
                return ResourceManager.GetString("ShowDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полупрозрачный режим.
        /// </summary>
        internal static string ShowTransparent {
            get {
                return ResourceManager.GetString("ShowTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиксировать.
        /// </summary>
        internal static string Snap {
            get {
                return ResourceManager.GetString("Snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать снимок реперного изображения.
        /// </summary>
        internal static string SnapEx {
            get {
                return ResourceManager.GetString("SnapEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук включен.
        /// </summary>
        internal static string SoundOn {
            get {
                return ResourceManager.GetString("SoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук включен. Отключить микрофон.
        /// </summary>
        internal static string SoundOnEx {
            get {
                return ResourceManager.GetString("SoundOnEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка передачи видео/аудио! Проверьте связь с компьютером пациента..
        /// </summary>
        internal static string StreamBroken {
            get {
                return ResourceManager.GetString("StreamBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль доктора.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line options.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикрепить видео.
        /// </summary>
        internal static string VideoAttach {
            get {
                return ResourceManager.GetString("VideoAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открепить видео.
        /// </summary>
        internal static string VideoDetach {
            get {
                return ResourceManager.GetString("VideoDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание сетевого соединения.
        /// </summary>
        internal static string WaitingForNetCon {
            get {
                return ResourceManager.GetString("WaitingForNetCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить видео.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
